name: CI Backend EzPay

on:
  push:
    branches: [ development ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "remote server"
      with:
        host: ${{ secrets.HOST_SSH }}
        username: ${{ secrets.USERNAME_SSH }}
        password: ${{ secrets.PASSWORD_SSH }}
        script: whoami
